from Lista_duplamente_encadeada.lista_duplamente_encadeada import ListaDuplamente

lista = ListaDuplamente()
print(lista)
print("Tamanho da lista:",lista.tamanho)
lista.adicionar(8)
lista.adicionar(3)
lista.adicionar(9)
lista.adicionar(1)
lista.adicionar(14)
lista.adicionar(5)
lista.adicionar(4)
lista.adicionar(13)
lista.adicionar(2)
lista.adicionar(7)
lista.adicionar(11)
lista.adicionar(12)
lista.adicionar(10)
lista.adicionar(15)

print("============================================")
print("Lista após os valores adicionados:")
print(lista)
print("Tamanho da lista:",lista.tamanho)
lista.adicionar_index(0, 4)
lista.adicionar_index(5, 6)
lista.adicionar_index(9, 10)
lista.adicionar_index(4, 13)
lista.adicionar_index(5, 8)
lista.adicionar_index(34, 1)
print("============================================")
print("Lista após os valores adicionados:")
print(lista)
print("Tamanho da lista:",lista.tamanho)
print("============================================")
lista.remove_index(4)
lista.remove_index(10)
print("Lista após os valores removidos:")
print(lista)
print("Tamanho da lista:",lista.tamanho)
print("============================================")
print("Valor presente na posição indicada pelo get_valor:",lista.get_valor(15))
print("Índice do valor indicado pelo get_index:", lista.get_index(14))
print("============================================")
lista.remove_valor(8)
lista.remove_valor(4)
lista.remove_valor(1)
print("Lista após os valores removidos:")
print(lista)
print("Tamanho da lista:",lista.tamanho)
print("============================================")
print("A função get_lista_invertida apenas printa a lista invertida:")
print(lista.get_lista_invertida())
print("============================================")
print("Lista Normal:")
print(lista)
print("Tamanho da lista:",lista.tamanho)
print("============================================")
lista.ordenar()
print("Lista ordenada:")
print(lista)
print("Tamanho da lista:",lista.tamanho)
print("============================================")
lista.inverter()
print("Lista invertida:")
print(lista)
print("Tamanho da lista:",lista.tamanho)

